steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - '--build-arg'
      - 'SENTRY_RELEASE=${COMMIT_SHA}'
      - .
      - '-f'
      - murmuration/Dockerfile
    id: Build Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
    id: Push Image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - start-update
      - murmuration-goldfinch-finance-3
      - '--version=template=murmuration-goldfinch-finance-7'
      - '--zone=us-central1-a'
    entrypoint: gcloud
    id: Update Template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - replace
      - murmuration-goldfinch-finance-3
      - '--zone=us-central1-a'
    entrypoint: gcloud
    id: Replace Instance
timeout: '1600s'
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE
  machineType: E2_HIGHCPU_32
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _SERVICE_NAME: murmuration-goldfinch-finance
