[profile.default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
bytecode_hash = 'ipfs'
cache = true
cache_path = 'foundry-cache'
evm_version = 'london'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_test_rejects = 65536
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_reports = ['*']
ignored_error_codes = [1878]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ["node_modules", "lib"]
memory_limit = 33554432
names = false
no_storage_caching = false
offline = false
optimizer = true
# Uncomment the next line to fix "Stack too deep" issues with `forge coverage`
# optimizer_details.yul = true
optimizer_runs = 200
out = 'artifacts'
remappings = []
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = false
sparse_mode = false
src = 'contracts'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 0
via_ir = false
fs_permissions = [{ access = "read", path = "./artifacts/" }, { access = "read", path = './contracts/test/fixtures' }]
no_match_path="./test/forge/mainnet/*.t.sol"
max_test_rejects = 131072 # double the default

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[profile.mainnet-forking]
match_path = "./test/forge/mainnet/*.t.sol"
block_number = 15626901
fork_block_number = 15626901
