import path from "path"
import fs from "fs"

import devDeployments from "../../protocol/deployments/all_dev.json"
import mainnetDeployments from "../../protocol/deployments/all.json"

const localhostContracts = devDeployments["31337"].localhost.contracts
const mainnetContracts = mainnetDeployments["1"].mainnet.contracts

console.log("Updating the address manifest")

const code = `
// This file is automatically generated
import {dataSource} from "@graphprotocol/graph-ts"

export const STAKING_REWARDS_ADDRESS = dataSource.network() == "mainnet" ? "${mainnetContracts.StakingRewards.address.toLowerCase()}" : "${localhostContracts.StakingRewards.address.toLowerCase()}";
export const POOL_TOKENS_ADDRESS = dataSource.network() == "mainnet" ? "${mainnetContracts.PoolTokens.address.toLowerCase()}" : "${localhostContracts.PoolTokens.address.toLowerCase()}";
`
fs.writeFileSync(path.resolve(__dirname, "../src/address-manifest.ts"), code)

console.log("Finished updating the address manifest")
