export const CHAIN_IDS_BY_NAME = {
  OPTIMISM_MAINNET: 10,
  OPTIMISM_GOERLI_TESTNET: 420,
  HARDHAT_TESTNET: 31337,
  ARBITRUM_ONE_MAINNET: 42161,
  ARBITRUM_NITRO_GOERLI_TESTNET: 421613,
  BASE_MAINNET: 8453,
  BASE_GOERLI_TESTNET: 84531,
}

export const CHAIN_IDS = Object.values(CHAIN_IDS_BY_NAME)
export type ChainId = (typeof CHAIN_IDS)[number]
