import {assertNonEmptyArray, assertNonNullable} from "@goldfinch-eng/utils"
import {generateMerkleRoot} from "../../../../blockchain_scripts/merkle/merkleDirectDistributor/generateMerkleRoot"
import {
  JsonAccountedDirectGrant,
  MerkleDirectDistributorGrantInfo,
  MerkleDirectDistributorInfo,
} from "../../../../blockchain_scripts/merkle/merkleDirectDistributor/types"
import {verifyMerkleRoot} from "../../../../blockchain_scripts/merkle/merkleDirectDistributor/verifyMerkleRoot"
import {genDifferentHexString} from "../../../testHelpers"
import fixtures from "./fixtures"

const genInvalidMerkleDirectDistributorInfo = (
  genInvalidLastGrantInfo: (lastGrantInfo: MerkleDirectDistributorGrantInfo) => MerkleDirectDistributorGrantInfo
): MerkleDirectDistributorInfo => {
  const grants = fixtures.output.grants.slice()
  const last = grants[grants.length - 1]
  assertNonNullable(last)
  const invalidLastGrantInfo = genInvalidLastGrantInfo(last)
  grants[grants.length - 1] = invalidLastGrantInfo
  const json: MerkleDirectDistributorInfo = {
    ...fixtures.output,
    grants,
  }
  return json
}

describe("verifyMerkleRoot", () => {
  it("rejects invalid JSON", async () => {
    const json = {
      ...fixtures.output,
      merkleRoot: 1001,
    }
    expect(() => verifyMerkleRoot(json)).to.throw("Invalid JSON.")
  })

  it("rejects an invalid index for a grant", async () => {
    const json = genInvalidMerkleDirectDistributorInfo((lastGrantInfo) => ({
      ...lastGrantInfo,
      index: lastGrantInfo.index + 1,
    }))
    expect(() => verifyMerkleRoot(json)).to.throw("Failed validation for 1 or more proofs")
  })

  it("rejects an invalid amount for a grant", async () => {
    const json = genInvalidMerkleDirectDistributorInfo((lastGrantInfo) => ({
      ...lastGrantInfo,
      grant: {
        ...lastGrantInfo.grant,
        amount: genDifferentHexString(lastGrantInfo.grant.amount),
      },
    }))
    expect(() => verifyMerkleRoot(json)).to.throw("Failed validation for 1 or more proofs")
  })

  it("rejects an invalid (empty) proof array for a grant", async () => {
    const json = genInvalidMerkleDirectDistributorInfo((lastGrantInfo) => ({
      ...lastGrantInfo,
      proof: [],
    }))
    expect(() => verifyMerkleRoot(json)).to.throw("Failed validation for 1 or more proofs")
  })

  it("rejects an invalid (empty) proof string for a grant", async () => {
    const json = genInvalidMerkleDirectDistributorInfo((lastGrantInfo) => {
      const invalidProof: string[] = lastGrantInfo.proof.slice()
      assertNonEmptyArray(invalidProof)
      invalidProof[invalidProof.length - 1] = web3.utils.asciiToHex("")
      return {
        ...lastGrantInfo,
        proof: invalidProof,
      }
    })
    expect(() => verifyMerkleRoot(json)).to.throw("invalid value for bytes32")
  })

  it("rejects an invalid (non-empty) proof string for a grant", async () => {
    const json = genInvalidMerkleDirectDistributorInfo((lastGrantInfo) => {
      const invalidProof: string[] = lastGrantInfo.proof.slice()
      const lastElement = invalidProof[invalidProof.length - 1]
      assertNonNullable(lastElement)
      invalidProof[invalidProof.length - 1] = genDifferentHexString(lastElement)
      return {
        ...lastGrantInfo,
        proof: invalidProof,
      }
    })
    expect(() => verifyMerkleRoot(json)).to.throw("Failed validation for 1 or more proofs")
  })

  it("rejects an invalid root", async () => {
    const differentRoot = genDifferentHexString(fixtures.output.merkleRoot)
    const json: MerkleDirectDistributorInfo = {
      ...fixtures.output,
      merkleRoot: differentRoot,
    }

    expect(() => verifyMerkleRoot(json)).to.throw("Failed validation for 1 or more proofs")
  })

  it("verifies a valid root", async () => {
    const json: MerkleDirectDistributorInfo = fixtures.output

    const verificationResult = verifyMerkleRoot(json)
    expect(verificationResult).to.eql({
      reconstructedMerkleRoot: json.merkleRoot,
      matchesRootInJson: true,
    })
  })

  it("verifies a root generated by `generateMerkleRoot()`", async () => {
    const json: JsonAccountedDirectGrant[] = fixtures.input
    const merkleDistributorInfo = generateMerkleRoot(json)
    expect(merkleDistributorInfo).to.eql(fixtures.output)
    const verificationResult = verifyMerkleRoot(merkleDistributorInfo)
    expect(verificationResult).to.eql({
      reconstructedMerkleRoot: merkleDistributorInfo.merkleRoot,
      matchesRootInJson: true,
    })
  })
})
