/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { SeniorPool } from "./SeniorPool";

export { Erc20__factory } from "./factories/Erc20__factory";
export { SeniorPool__factory } from "./factories/SeniorPool__factory";
